[project]
name = "fast-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ohmartin", email = "ohmartin@bancolombia.com.co" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standar,standard]>=0.142.2",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
]

[project.scripts]
fast-api = "fast_api:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
